### ISSUE TITLE
package didn't work for me

### ISSUE THREAD

**Issue by avl055** [artwells/meteor-accounts-guest#24]
I20150422-01:15:55.945(1)? Exception while invoking method 'createGuest' TypeError: Object #<Object> has no method 'createUser'
I20150422-01:15:55.946(1)?     at [object Object].Meteor.methods.createGuest (packages/artwells:accounts-guest/accounts-guest-server.js:37:1)
I20150422-01:15:55.946(1)?     at maybeAuditArgumentChecks (packages/ddp/livedata_server.js:1617:1)
I20150422-01:15:55.946(1)?     at packages/ddp/livedata_server.js:648:1
I20150422-01:15:55.946(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150422-01:15:55.946(1)?     at packages/ddp/livedata_server.js:647:1
I20150422-01:15:55.947(1)?     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
I20150422-01:15:55.947(1)?     at [object Object]._.extend.protocol_handlers.method (packages/ddp/livedata_server.js:646:1)
I20150422-01:15:55.947(1)?     at packages/ddp/livedata_server.js:546:1

**Comment by avl055** [comment]
ok, it's that I removed "accounts-base", this was causing this issue. So my bad, though would be nice to somehow manage dependencies here! 

cheers!
