### ISSUE TITLE
match is not defined?

### ISSUE THREAD

**Issue by lynerjy** [artwells/meteor-accounts-guest#43]
Hi, I'm getting this error whenever i go to my page:

 Exception while invoking method 'login' ReferenceError: Match is not defined 
at createGuestOptions (packages/artwells_accounts-guest/packages/artwells_accounts-guest.js:143:1)
at [object Object].LoginState.addSignedUpInterceptor.user.loginStateSignedUp (packages/artwells_accounts-guest/packages/artwells_accounts-guest.js:65:1) 
 at accounts_server.js:462:32
 at tryLoginMethod (accounts_server.js:239:14)
 at AccountsServer.Ap._runLoginHandlers (accounts_server.js:459:18)
 at [object Object].methods.login (accounts_server.js:522:27)
 at maybeAuditArgumentChecks (livedata_server.js:1692:12)
 at livedata_server.js:708:19
 at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
 at livedata_server.js:706:40

(i suspect my being brand new to meteor may have some role in this)

**Comment by jordanbuchman** [comment]
Add the `check` package.

**Comment by artwells** [comment]
check is in packages.js
