### ISSUE TITLE
package ignoring ian:accounts-ui-bootstrap-3

### ISSUE THREAD

**Issue by jdmswong** [artwells/meteor-accounts-guest#53]
App threw this error when page opened:
``` 
Exception while invoking method 'login' Error: Can't create a guest user with falsey AccountsGuest.anonymous unless the accounts-password package is installed.
 Either set AccountsGuest.anonymous or run 'meteor add accounts-password'.
     at [object Object].LoginState.addSignedUpInterceptor.user.loginStateSignedUp (packages/artwells_accounts-guest/packages/artwells_accounts-guest.js:62:1)
     at accounts_server.js:462:32
     at tryLoginMethod (accounts_server.js:239:14)
     at AccountsServer.Ap._runLoginHandlers (accounts_server.js:459:18)
     at [object Object].methods.login (accounts_server.js:522:27)
     at maybeAuditArgumentChecks (livedata_server.js:1698:12)
     at livedata_server.js:708:19
     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
     at livedata_server.js:706:40
     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
```

except that
```
ian:accounts-ui-bootstrap-3  1.2.89  Bootstrap-styled accounts-ui with multi-language support.
```
has been added to my project

Using Meteor 1.2.1

**Comment by jdmswong** [comment]
```AccountsGuest.anonymous = true;```
